<?php $buttonTitle = __('Contact for sale price'); ?>
<div class="box-tocart">
    <div class="fieldset">
        <div class="actions">
            <button type="submit" title="<?= $block->escapeHtmlAttr($buttonTitle) ?>" class="action primary contact-for-sale-price" id="primary contact-for-sale-price">
                <span><?= $block->escapeHtml($buttonTitle) ?></span>
            </button>
        </div>
    </div>
</div>